/* THIS FILE IS AUTO-GENERATED by generate-icons.ts */
import CheckIcon from './check.svg';
import CheckFinIcon from './checkFin.svg';

export const iconsMap = {
  'check': CheckIcon,
  'checkFin': CheckFinIcon,
} as const;

export type IconName = keyof typeof iconsMap;
export type IconComponent = (typeof iconsMap)[IconName];
